from .paths import (
    PROJECT_ROOT,
    RESOURCES_DIR,
    ASSETS_DIR,
    BLOCK_TEXTURES_DIR,
    DEHUMIDIFIER_TEXTURES_DIR,
    AIR_PURIFIER_TEXTURES_DIR,
    DETECTORS_TEXTURES_DIR,
    MOLD_TEXTURES_DIR,
    BLOCK_MODELS_DIR,
    DEHUMIDIFIER_MODELS_DIR,
    BLOCKSTATES_DIR
)
